---
# tasks file for kibana
- name: install kibana Ubuntu
  apt:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: run daemon-reload for kibana
  systemd: daemon_reload=yes
  when: ansible_distribution == "Ubuntu"

- name: Enable service Kibana
  systemd:
    name: kibana
    enabled: yes
  when: ansible_distribution  == "Ubuntu"

- name: install Kibana CentOS
  yum:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Run daemon-reload for kibana CentOS
  systemd: daemon-reload=yes
  when: ansible_distribution == "CentOS"

- name: Enable service Kibana CentOS
  systemd:
    name: kibana
    enabled: yes
  when: ansible_distribution == "CentOS"
